import Head from 'next/head'
import {Inter} from '@next/font/google'
import {Line, LineChart, Tooltip, XAxis, YAxis} from 'recharts';
import {bankBalances} from "@/data";
import {BankChart} from "@/components/BankChart";


const inter = Inter({subsets: ['latin']})

export default function Home() {

    const sortedKeys = Object.keys(bankBalances).sort()
    const data = bankBalances.bankOfAmerica.nonTaxGenOpsx9068.sort((a, b) => {
        return new Date(b[0]).getDate() - new Date(a[0]).getDate()
    }).map((item) => {
        return {
            date: item[0],
            balance: item[1]
        }
    })
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div>
                <div>
                    {
                        Object.entries(bankBalances).map(([bankName, account]) => {
                            return Object.entries(account).map(([accountName, accountData]) => {
                                return <BankChart bankName={bankName} accountName={accountName} accountData={accountData} key={`${bankName}-${accountName}}`}/>
                            })
                        })
                    }
                </div>
            </div>
        </>
    )
}
