import Head from 'next/head'
import {bankBalances, legalEntities} from "@/data";
import React from "react";
import dynamic from 'next/dynamic'

const LegalEntityChart = dynamic(() =>
    import('@/components/LegalEntityChart').then((mod) => mod.LegalEntityChart), {ssr: false}
)
const BankChart = dynamic(() =>
    import('@/components/BankChart').then((mod) => mod.BankChart), {ssr: false}
)


export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div style={{overflow: "hidden"}}>
                <div>
                    <BankChart bankData={bankBalances}/>
                </div>
                <div>
                    <LegalEntityChart legalEntities={legalEntities} />
                </div>
            </div>
        </>
    )
}
